### PR TITLE
SodukoSolver

### PR DESCRIPTION
**Pull request by aditi10701**
Kindly accept this PR

### CODE REVIEW

**Comment by markandey007** [comment]
please follow the id and mssg here i will merge it after 2 days bcs more than 150 pr are pending

**Comment by aditi10701** [comment]
done

**Comment by aditi10701** [comment]
> please follow the id and mssg here i will merge it after 2 days bcs more than 150 pr are pending

When will it be considered as a successful PR?

**Comment by aditi10701** [comment]
.

**Pull request closed without merging**
