### PR TITLE
Wrote the code for Kruskal's algorithm for MST in C++ 

### PR DESCRIPTION
**Pull request by sidhantsemwal**

### CODE REVIEW

**Comment by markandey007** [comment]
GREAT I AM MERGING UR PR PLEASE FOLLOW THE ID AND FORK THIS REPO

**Comment by markandey007** [comment]
@sidhantsemwal

**Comment by sidhantsemwal** [comment]
> GREAT I AM MERGING UR PR PLEASE FOLLOW THE ID AND FORK THIS REPO

Yeah , done :)

**Comment by sidhantsemwal** [comment]
@markandey007  can you add the hacktoberfest-accepted label ?

**Pull request merged**
